### ISSUE TITLE
 Error building libwebsockets with OpenSSL via FetchContent

### ISSUE THREAD

**Issue by ComeClose322** [jimmy-park/openssl-cmake#21]
Hi,
I am trying to build libwebsockets with OpenSSL using FetchContent in CMake.
Here is the relevant part of my CMakeLists.txt:
```cmake
set(BUILD_OPENSSL ON)
set(OPENSSL_BUILD_VERSION 3.3.2)

FetchContent_Declare(
    openssl-cmake
    URL https://github.com/jimmy-park/openssl-cmake/archive/main.tar.gz
)
FetchContent_MakeAvailable(openssl-cmake)

set(LWS_WITH_SSL ON CACHE BOOL "" FORCE)   

FetchContent_Declare(
  libwebsockets
  GIT_REPOSITORY https://github.com/warmcat/libwebsockets.git
  GIT_TAG v4.3-stable
  GIT_SHALLOW TRUE
  GIT_PROGRESS TRUE
)
FetchContent_MakeAvailable(libwebsockets)
```

From the logs, I can see that libwebsockets found the openssl-cmake headers and library locations:

```logs
[cmake] Git commit hash: 5102a5c
[cmake] Compiling with SSL support
[cmake] OpenSSL include dir: .../MYPROJECTDIR/build/_deps/openssl-source-src/include;.../MYPROJECTDIR/build/_deps/openssl-source-build/include
[cmake] OpenSSL libraries: .../MYPROJECTDIR/build/_deps/openssl-source-build/libcrypto.lib;.../MYPROJECTDIR/build/_deps/openssl-source-build/libssl.lib
```

However, CMake then throws the following error:
```logs
[cmake] CMake Error in build/_deps/libwebsockets-src/lib/CMakeLists.txt:
[cmake]   Target "websockets_shared" INTERFACE_INCLUDE_DIRECTORIES property contains
[cmake]   path:
[cmake] 
[cmake]     .../MYPROJECTDIR/build/_deps/openssl-source-src/include"
[cmake] 
[cmake]   which is prefixed in the build directory.
```
How can i fix it?

**Comment by jimmy-park** [comment]
I think libwebsockets has a problem with `target_include_directories()` when exporting CMake targets.
Could you build with `set(LWS_WITH_EXPORT_LWSTARGETS OFF)`?

**Comment by jimmy-park** [comment]
And you should add `add_dependencies(websockets OpenSSL::SSL)` after `FetchContent_MakeAvailable(libwebsockets)` to correct the build order.

**Comment by ComeClose322** [comment]
Thank you! That helped to get rid of that error.
However, now I'm facing issues during the build process. I'm not sure which library is causing the problem, but when I try to build my application with openssl-cmake, I get the following error:
```logs
[build] .../build/_deps/libwebsockets-src/include/libwebsockets/lws-genhash.h:85:18: error: field has incomplete type 'HMAC_CTX' (aka 'struct hmac_ctx_st')
[build]         HMAC_CTX ctx;
[build]                  ^
[build] /Users/orlovmaxim/Documents/Games/BattleWater/build/_deps/openssl-source-src/include/openssl/types.h:135:16: note: forward declaration of 'struct hmac_ctx_st'
[build] typedef struct hmac_ctx_st HMAC_CTX;
[build]
```
But if I try to build with the OpenSSL installed on my system via Homebrew, the compilation succeeds.

I tried googling it and found this page: https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.cmake.md, specifically, the second section.

Does this mean that openssl-cmake is failing libwebsocket`s checks for openssl version?

**Comment by ComeClose322** [comment]
Sorry, I accidentally closed it.

**Comment by jimmy-park** [comment]
I found that libwebsockets requires the pre-built OpenSSL library in its CMake configuration.
In this case, it needs to build OpenSSL before the libwebsockets configuration.

**Comment by ComeClose322** [comment]
So Do i need to build it manually and install in some project directory before using project's cmake?

**Comment by jimmy-park** [comment]
Yes... I can't think of a better way right now.

**Comment by ComeClose322** [comment]
Thanks for help!
