### ISSUE TITLE
MSVC build failure

### ISSUE THREAD

**Issue by iGwkang** [jimmy-park/openssl-cmake#23]
```
 "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Auxiliary\Build\vcvarsall.bat" x64 && "C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x64/nmake.exe" /NOLOGO /S build_libs"
[build] **********************************************************************
[build] ** Visual Studio 2022 Developer Command Prompt v17.10.5
[build] ** Copyright (c) 2022 Microsoft Corporation
[build] **********************************************************************
[build] [vcvarsall.bat] Environment initialized for: 'x64'
[build] NMAKE : fatal error U1073: 不知道如何生成“"..\..\..\.cache\CPM\openssl-source\6ea3ef51de42a6e1e687c62177b17c1458a425ee\apps\apps.c"”
[build] Stop.
[build] NMAKE : fatal error U1077: “"C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.40.33807\bin\Hostx64\x64\nmake.exe" /LS                 depend && "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.40.33807\bin\Hostx64\x64\nmake.exe" /LS                 _build_libs”: 返回代码“0x2”
[build] Stop.
[build] ninja: build stopped: subcommand failed.
```

```cmake
  if (WIN32)
      set(openssl_target_platform "VC-WIN64A")
  else()
      set(openssl_target_platform "linux-aarch64")
  endif()

  CPMAddPackage(
      NAME openssl-cmake
      GIT_TAG 3.4.0
      GITHUB_REPOSITORY jimmy-park/openssl-cmake
      OPTIONS
          "OPENSSL_TARGET_VERSION 1.1.1w" "OPENSSL_TARGET_PLATFORM ${openssl_target_platform}"
          "OPENSSL_CONFIGURE_OPTIONS no-shared;no-tests"
      )
```

**Comment by jimmy-park** [comment]
Could you configure CMake with `-DOPENSSL_USE_CCACHE=OFF` for now?

**Comment by iGwkang** [comment]
```
[build] **********************************************************************
[build] ** Visual Studio 2022 Developer Command Prompt v17.10.5
[build] ** Copyright (c) 2022 Microsoft Corporation
[build] **********************************************************************
[build] [vcvarsall.bat] Environment initialized for: 'x64'
[build] ccache: error: execute_noreturn of C:/Program failed: No such file or directory
[build] NMAKE : fatal error U1077: “ccache C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x64/cl.exe  /MT /Zl /Gs0 /GF /Gy /W0 /wd4090 /nologo /O2 /I "." /I "include" /I "..\..\..\.cache\CPM\openssl-source\6ea3ef51de42a6e1e687c62177b17c1458a425ee" /I "..\..\..\.cache\CPM\openssl-source\6ea3ef51de42a6e1e687c62177b17c1458a425ee\include" -D"L_ENDIAN" -D"OPENSSL_PIC" -D"OPENSSL_CPUID_OBJ" -D"OPENSSL_IA32_SSE2" -D"OPENSSL_BN_ASM_MONT" -D"OPENSSL_BN_ASM_MONT5" -D"OPENSSL_BN_ASM_GF2m" -D"SHA1_ASM" -D"SHA256_ASM" -D"SHA512_ASM" -D"KECCAK1600_ASM" -D"RC4_ASM" -D"MD5_ASM" -D"AESNI_ASM" -D"VPAES_ASM" -D"GHASH_ASM" -D"ECP_NISTZ256_ASM" -D"X25519_ASM" -D"POLY1305_ASM" -D"OPENSSLDIR=\"C:\\Program Files\\Common Files\\SSL\"" -D"ENGINESDIR=\"C:\\Program Files\\OpenSSL\\lib\\engines-1_1\"" -D"OPENSSL_SYS_WIN32" -D"WIN32_LEAN_AND_MEAN" -D"UNICODE" -D"_UNICODE" -D"_CRT_SECURE_NO_DEPRECATE" -D"_WINSOCK_DEPRECATED_NO_WARNINGS" -D"NDEBUG"  -c /Foapps\app_rand.obj "..\..\..\.cache\CPM\openssl-source\6ea3ef51de42a6e1e687c62177b17c1458a425ee\apps\app_rand.c"”: 返回代码“0x1”
[build] Stop.
```


```cmake
    CPMAddPackage(
        NAME openssl-cmake
        GIT_TAG c065c85269f979ba60c6ebfc513215bbe38b8b17
        GITHUB_REPOSITORY jimmy-park/openssl-cmake
        OPTIONS
            "OPENSSL_TARGET_VERSION 1.1.1w" "OPENSSL_TARGET_PLATFORM ${openssl_target_platform}"
            "OPENSSL_CONFIGURE_OPTIONS no-shared;no-tests"
        )
```

**Comment by jimmy-park** [comment]
Could you clean the build directory and rebuild again with `-DOPENSSL_CONFIGURE_VERBOSE=ON`? And please share the result of OpenSSL configuration.

**Comment by iGwkang** [comment]
> Could you clean the build directory and rebuild again with `-DOPENSSL_CONFIGURE_VERBOSE=ON`? And please share the result of OpenSSL configuration.

This is because the default installation path of MSVC contains spaces.
I have fixed it.
https://github.com/jimmy-park/openssl-cmake/pull/25

**Comment by jimmy-park** [comment]
That's weird because the generated makefile should have `CC=cl` on Windows, not the full path of MSVC.

https://github.com/openssl/openssl/blob/1d160dbf39fbdba89389ddff54e45bacf278b04a/Configurations/10-main.conf#L1524C9-L1524C34

**Comment by iGwkang** [comment]
From the generated makefile, it is the full path.

**Comment by jimmy-park** [comment]
I did not touch `CMAKE_C_COMPILER` when configuring OpenSSL. Did you set the `CC` environment variable on your machine?

**Comment by iGwkang** [comment]
no, I did not actively set the CC environment variable.
![image](https://github.com/user-attachments/assets/0755a5cb-9055-4980-aff8-8deae957f4b6)

In `vscode`, using the `cmake plugin` will automatically execute `cmake . -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_INSTALL_PREFIX=../install --no-warn-unused-cli -Bbuild -G Ninja`

**Comment by jimmy-park** [comment]
I think Ninja generator will not work on Windows.
Could you try following commands on PowerShell?

```shell
cmake --preset windows
cmake --build --preset windows
```

**Comment by iGwkang** [comment]
I haven't used the `CMakePresets`, but I'm sure Ninja works because I've been developing with it for a long time.

**Comment by jimmy-park** [comment]
I mean `openssl-cmake`'s target detection relies on Visual Studio generators.
Sorry to bother you again, does `echo $env:CC` or `echo $env:CXX` show nothing on your machine?

**Comment by iGwkang** [comment]
![image](https://github.com/user-attachments/assets/623897c9-be97-4561-b06b-259a963c7573)

I haven't modified the environment variables.

**Comment by jimmy-park** [comment]
`%CC%` isn't working on PowerShell. You should use `echo $env:variable`.

**Comment by iGwkang** [comment]
@jimmy-park I'm sure it's not a problem with my machine's environment variables!

**Comment by jimmy-park** [comment]
I asked it just in case. Because I have no idea why `CC` is an absolute path.
Do you have any clues?

**Comment by iGwkang** [comment]
![image](https://github.com/user-attachments/assets/fa56273f-973a-4edf-bcdc-b4e8da3a4868)

https://github.com/jimmy-park/openssl-cmake/pull/24  Your modification this time will generate a makefile similar to this

**Comment by jimmy-park** [comment]
Does it work without appended `ccache`?

**Comment by iGwkang** [comment]
This has nothing to do with `ccache`
I tried using `-G "Visual Studio 17 2022" -T host=x64 -A x64`
The result is this:
![image](https://github.com/user-attachments/assets/1d3b72d4-2b3d-4789-8861-fd309dcc0039)
So I guess `Ninja` set `CC` to the full path!

**Comment by iGwkang** [comment]
But I think full absolute paths should be supported.
https://github.com/jimmy-park/openssl-cmake/pull/25 Solved it.

**Comment by jimmy-park** [comment]
Thanks for investigating this issue! I'll merge #25 after running some workflows.

**Comment by iGwkang** [comment]
OK, good night!
