### ISSUE TITLE
Add support of `CMAKE_OSX_DEPLOYMENT_TARGET` option

### ISSUE THREAD

**Issue by jue-jue-zi** [jimmy-park/openssl-cmake#4]
In order to compile object files adapted to older macos versions, the `CMAKE_OSX_DEPLOYMENT_TARGET` option is generally add to the CMakeLists.txt as below,

```
if(APPLE)
    set(CMAKE_OSX_DEPLOYMENT_TARGET "11.0")
endif()
```

But this only works in CMake projects. As the openssl uses the `./configure` file, [the `-mmacosx-version-min` flag is not actually passed to the `./configure` command](https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_DEPLOYMENT_TARGET.html). I've tried to add the following part to `openssl-cmake/CMakeLists.txt`, and it works,

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 5343bb4..e7d60e1 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -185,6 +185,10 @@ if(OPENSSL_USE_STATIC_LIBS)
     list(APPEND OPENSSL_CONFIGURE_OPTIONS no-shared)
 endif()
 
+if(APPLE AND CMAKE_OSX_DEPLOYMENT_TARGET)
+    list(APPEND OPENSSL_CONFIGURE_OPTIONS -mmacosx-version-min=${CMAKE_OSX_DEPLOYMENT_TARGET})
+endif()
+
 list(SORT OPENSSL_CONFIGURE_OPTIONS)
 list(REMOVE_DUPLICATES OPENSSL_CONFIGURE_OPTIONS)
 list(PREPEND OPENSSL_CONFIGURE_OPTIONS ${OPENSSL_TARGET_PLATFORM})
```

I wonder if there is any more suitable implements could help supporting the `CMAKE_OSX_DEPLOYMENT_TARGET` option.

**Comment by jimmy-park** [comment]
Thanks for suggestion.
But I won't add those options because they could be duplicated or conflict with other users' options.
And your modification is applied to iOS targets incorrectly since they need `-mios-version-min` or `-mios-simulator-version-min`.
If you really want to target macOS only, don't use the `APPLE` variable but `CMAKE_SYSTEM_NAME`.

```cmake
if(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
    set(CMAKE_OSX_DEPLOYMENT_TARGET 11.0)
    list(APPEND OPENSSL_CONFIGURE_OPTIONS -mmacosx-version-min=${CMAKE_OSX_DEPLOYMENT_TARGET})
endif()
```

**Comment by jue-jue-zi** [comment]
> ```cmake
> if(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
>     list(APPEND OPENSSL_CONFIGURE_OPTIONS -mmacosx-version-min=${CMAKE_OSX_DEPLOYMENT_TARGET})
> endif()
> ```

Thanks for your suggestions. I've tried to add these to the CMakeLists.txt of the top project, but `if(CMAKE_SYSTEM_NAME STREQUAL "Darwin")` cannot work in my macOS. After changed to `if(APPLE)`, the `list` command can work.

**Comment by jimmy-park** [comment]
Could you find how `CMAKE_SYSTEM_NAME` is actually defined on your system?

**Comment by jue-jue-zi** [comment]
> Could you find how `CMAKE_SYSTEM_NAME` is actually defined on your system?

```
$ cmake --system-information | grep CMAKE_SYSTEM_NAME      
CMAKE_SYSTEM_NAME == "Darwin"
CMAKE_SYSTEM_NAME "Darwin"
PRESET_CMAKE_SYSTEM_NAME "FALSE"
```

But it's weird the var `CMAKE_SYSTEM_NAME` outputs "" in cmake config stage (`cmake -B build`).

**Comment by jimmy-park** [comment]
I think the Xcode generator isn't selected. Could you try `cmake -B build -G Xcode`?

**Comment by jue-jue-zi** [comment]
> I think the Xcode generator isn't selected. Could you try `cmake -B build -G Xcode`?

Yes, Ninja is used bty default. The CMAKE_SYSTEM_NAME can be set correctly only if the Xcode generator is selected?

**Comment by jimmy-park** [comment]
It could be empty before `project()` command. If `CMAKE_SYSTEM_NAME` is empty, it is set to `CMAKE_HOST_SYSTEM_NAME` after `project()`. I guess Xcode generator sets `CMAKE_SYSTEM_NAME` to `Darwin`.

**Comment by jue-jue-zi** [comment]
> It could be empty before `project()` command. If `CMAKE_SYSTEM_NAME` is empty, it is set to `CMAKE_HOST_SYSTEM_NAME` after `project()`. I guess Xcode generator sets `CMAKE_SYSTEM_NAME` to `Darwin`.

Yes! After `project()`, the `CMAKE_SYSTEM_NAME` is set even though Ninja is used. But the CMAKE doc ask to [set `CMAKE_OSX_DEPLOYMENT_TARGET` prior to the first `project()`](https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_DEPLOYMENT_TARGET.html). How to solve it?

**Comment by jimmy-park** [comment]
Through a cache variable. `cmake -B build -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0`

**Comment by jue-jue-zi** [comment]
> Through a cache variable. `cmake -B build -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0`

But the project needs to be compiled both in macOS and linux, if the `CMAKE_OSX_DEPLOYMENT_TARGET` is set by command line, it'll need to use different build scripts in different systems.

**Comment by jimmy-park** [comment]
It should be different command for each target platform, but I think `CMAKE_OSX_DEPLOYMENT_TARGET` will not affect other platforms.

**Comment by jue-jue-zi** [comment]
> It should be different command for each target platform, but I think `CMAKE_OSX_DEPLOYMENT_TARGET` will not affect other platforms.

Yes for a pure CMake project, but `-mmacosx-version-min=${CMAKE_OSX_DEPLOYMENT_TARGET}` is manually added to the openssl `C_FLAGS` by detecting `CMAKE_OSX_DEPLOYMENT_TARGET`.

**Comment by jimmy-park** [comment]
Isn't it okay if you append it under `if(CMAKE_SYSTEM_NAME STREQUAL "Darwin")`?

**Comment by jue-jue-zi** [comment]
> Isn't it okay if you append it under `if(CMAKE_SYSTEM_NAME STREQUAL "Darwin")`?

Great idea, thanks a lot!
