### ISSUE TITLE
how to build for cross platform like amd64-gnu

### ISSUE THREAD

**Issue by mun24** [jimmy-park/openssl-cmake#5]
Thx

**Comment by jimmy-park** [comment]
You can specify the target platform using the `OPENSSL_TARGET_PLATFORM` option.
Find the target you want in [OpenSSL's scripts](https://github.com/openssl/openssl/blob/master/Configurations/10-main.conf).

**Comment by mun24** [comment]
Hi,

Thanks for the prompt response. 

Before I was using https://github.com/janbar/openssl-cmake
but now I want to use your openssl-cmake bcoz I need new openssl 3

Can you pls guide me. Are you available on chat.


Thanks
Ajit





On Saturday, February 24, 2024 at 08:27:45 a.m. EST, Jiwoo Park ***@***.***> wrote: 







You can specify the target platform using the OPENSSL_TARGET_PLATFORM option.
Find the target you want in OpenSSL's scripts.

**Comment by jimmy-park** [comment]
If you're familiar with CMake, building OpenSSL with this project isn't a big deal.
But if you failed to building, just comment here with info such as command or screenshots.

**Comment by mun24** [comment]
Thanks for the response. I am not good in Cmake

I replaced previous openssl folder from yours, getting this error



Building OpenSSL
-- CPM: Adding package ***@***.*** (3.2.1)
-- Curruent configure options : linux-;no-tests
CMake Error at cmake/ConfigureOpenSSL.cmake:131 (message):
  linux- isn't supported
Call Stack (most recent call first):
  CMakeLists.txt:196 (configure_openssl)


-- Configuring incomplete, errors occurred!






On Saturday, February 24, 2024 at 10:47:18 a.m. EST, Jiwoo Park ***@***.***> wrote: 







If you're familiar with CMake, building OpenSSL with this project isn't a big deal.
But if you failed to building, just comment here with info such as command or screenshots.

**Comment by mun24** [comment]
May be if you make a simple higher level CMakeLists with  dependency of
openssl 3,
libssh2,
zlib
curl
 and make the build for this platform amd64-gnu and make it compilable
that will be very helpful for me


Thanks a lot.

Ajit






On Saturday, February 24, 2024 at 11:22:13 a.m. EST, Ajit Mittal ***@***.***> wrote: 





Thanks for the response. I am not good in Cmake

I replaced previous openssl folder from yours, getting this error



Building OpenSSL
-- CPM: Adding package ***@***.*** (3.2.1)
-- Curruent configure options : linux-;no-tests
CMake Error at cmake/ConfigureOpenSSL.cmake:131 (message):
  linux- isn't supported
Call Stack (most recent call first):
  CMakeLists.txt:196 (configure_openssl)


-- Configuring incomplete, errors occurred!






On Saturday, February 24, 2024 at 10:47:18 a.m. EST, Jiwoo Park ***@***.***> wrote: 







If you're familiar with CMake, building OpenSSL with this project isn't a big deal.
But if you failed to building, just comment here with info such as command or screenshots.

**Comment by jimmy-park** [comment]
>-- Curruent configure options : linux-;no-tests

It seems like detecting the target platform has failed.
It should be `linux-${CMAKE_SYSTEM_PROCESSOR}` which is `linux-x86_64` on your system.
Maybe `CMAKE_SYSTEM_PROCESSOR` wasn't set in the toolchain file?
You can also add `set(OPENSSL_TARGET_PLATFORM linux-x86_64)` before `add_subdirectory(your_openssl_dir)`.

>May be if you make a simple higher level CMakeLists with  dependency of
openssl 3,
libssh2,
zlib
curl
 and make the build for this platform amd64-gnu and make it compilable
that will be very helpful for me

This project is just a CMake wrapper of OpenSSL build scripts. Combining those libraries isn't the purpose of this project.

**Comment by mun24** [comment]
Hi

I was trying your cmake

I have a simple CMakeLists.txt

cmake_minimum_required(VERSION 3.23)
project(geometry LANGUAGES CXX)

set(CMAKE_C_FLAGS -pthread)
add_library(geo SHARED)

target_include_directories(geo PRIVATE "${PROJECT_SOURCE_DIR}")
add_subdirectory("shape")
add_subdirectory("square")

find_package(OpenSSL REQUIRED)
add_subdirectory("openssl-cmake")
add_subdirectory("libssh2")

add_executable(app)
target_sources(app PRIVATE "example/app.cpp")
target_link_libraries(app PRIVATE geo
OpenSSL::SSL
OpenSSL::Crypto
-ldl
libssh2::libssh2
 )

Let me know if there is any issue with it. I know you are not interested in libssh2. But my app is dependent on both openssl and libssh2. and also libssh2 is dependent on openssl. I am getting these errors now

------------
[ 39%] Linking C executable direct_tcpip
/usr/bin/ld: ../../_deps/openssl-source-build/libcrypto.a(libcrypto-lib-dso_dlfcn.o): in function `dlfcn_globallookup':
dso_dlfcn.c:(.text+0x17): undefined reference to `dlopen'
/usr/bin/ld: dso_dlfcn.c:(.text+0x2a): undefined reference to `dlsym'
/usr/bin/ld: dso_dlfcn.c:(.text+0x35): undefined reference to `dlclose'
/usr/bin/ld: ../../_deps/openssl-source-build/libcrypto.a(libcrypto-lib-dso_dlfcn.o): in function `dlfcn_bind_func':
dso_dlfcn.c:(.text+0x1cf): undefined reference to `dlsym'
/usr/bin/ld: dso_dlfcn.c:(.text+0x2ce): undefined reference to `dlerror'
/usr/bin/ld: ../../_deps/openssl-source-build/libcrypto.a(libcrypto-lib-dso_dlfcn.o): in function `dlfcn_load':
dso_dlfcn.c:(.text+0x345): undefined reference to `dlopen'
/usr/bin/ld: dso_dlfcn.c:(.text+0x3d0): undefined reference to `dlclose'
/usr/bin/ld: dso_dlfcn.c:(.text+0x401): undefined reference to `dlerror'
/usr/bin/ld: ../../_deps/openssl-source-build/libcrypto.a(libcrypto-lib-dso_dlfcn.o): in function `dlfcn_pathbyaddr':
dso_dlfcn.c:(.text+0x4d6): undefined reference to `dladdr'
/usr/bin/ld: dso_dlfcn.c:(.text+0x547): undefined reference to `dlerror'
/usr/bin/ld: ../../_deps/openssl-source-build/libcrypto.a(libcrypto-lib-dso_dlfcn.o): in function `dlfcn_unload':
dso_dlfcn.c:(.text+0x6d8): undefined reference to `dlclose'
collect2: error: ld returned 1 exit status

-------------------

It would b nice if you can give some tips to help me/


Thanks
Ajit






On Saturday, February 24, 2024 at 11:48:05 a.m. EST, Jiwoo Park ***@***.***> wrote: 







>  
> -- Curruent configure options : linux-;no-tests
> 

It seems like detecting the target platform has failed.
It should be linux-${CMAKE_SYSTEM_PROCESSOR} which is linux-x86_64 on your system.
Maybe CMAKE_SYSTEM_PROCESSOR wasn't set in the toolchain file?
You can also add set(OPENSSL_TARGET_PLATFORM linux-x86_64) before add_subdirectory(your_openssl_dir).

>  
> May be if you make a simple higher level CMakeLists with dependency of
> openssl 3,
> libssh2,
> zlib
> curl
> and make the build for this platform amd64-gnu and make it compilable
> that will be very helpful for me
> 

This project is just a CMake wrapper of OpenSSL build scripts. Combining those libraries isn't the purpose of this project.

**Comment by jimmy-park** [comment]
You should not call `find_package(OpenSSL REQUIRED)` before using `openssl-cmake`. It may link the system library. Try without `find_package`.

**Comment by mun24** [comment]
Thx for the prompt response.


I started from scratch and then first
cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF
cmake --build .

and then got the error below:

[  1%] Building CXX object CMakeFiles/geo.dir/shape/shape.cpp.o
[  2%] Building CXX object CMakeFiles/geo.dir/square/square.cpp.o
[  3%] Linking CXX shared library libgeo.so
[  3%] Built target geo
[  4%] Building C object libssh2/src/CMakeFiles/libssh2_shared.dir/agent.c.o
In file included from /home/user/test/cmake/shared_library/build/_deps/openssl-source-src/include/openssl/opensslconf.h:15,
                 from /home/user/test/cmake/shared_library/libssh2/src/openssl.h:81,
                 from /home/user/test/cmake/shared_library/libssh2/src/crypto.h:45,
                 from /home/user/test/cmake/shared_library/libssh2/src/libssh2_priv.h:183,
                 from /home/user/test/cmake/shared_library/libssh2/src/agent.c:42:
/home/user/test/cmake/shared_library/build/_deps/openssl-source-src/include/openssl/macros.h:147:4: error: #error "OPENSSL_API_COMPAT expresses an impossible API compatibility level"
  147 | #  error "OPENSSL_API_COMPAT expresses an impossible API compatibility level"
      |    ^~~~~
make[2]: *** [libssh2/src/CMakeFiles/libssh2_shared.dir/build.make:76: libssh2/src/CMakeFiles/libssh2_shared.dir/agent.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:362: libssh2/src/CMakeFiles/libssh2_shared.dir/all] Error 2
make: *** [Makefile:156: all] Error 2


Thanks for the help again.


Regards
Ajit


On Sunday, February 25, 2024 at 10:15:48 p.m. EST, Ajit Mittal ***@***.***> wrote: 





Hi

I was trying your cmake

I have a simple CMakeLists.txt

cmake_minimum_required(VERSION 3.23)
project(geometry LANGUAGES CXX)

set(CMAKE_C_FLAGS -pthread)
add_library(geo SHARED)

target_include_directories(geo PRIVATE "${PROJECT_SOURCE_DIR}")
add_subdirectory("shape")
add_subdirectory("square")

find_package(OpenSSL REQUIRED)
add_subdirectory("openssl-cmake")
add_subdirectory("libssh2")

add_executable(app)
target_sources(app PRIVATE "example/app.cpp")
target_link_libraries(app PRIVATE geo
OpenSSL::SSL
OpenSSL::Crypto
-ldl
libssh2::libssh2
 )

Let me know if there is any issue with it. I know you are not interested in libssh2. But my app is dependent on both openssl and libssh2. and also libssh2 is dependent on openssl. I am getting these errors now

------------
[ 39%] Linking C executable direct_tcpip
/usr/bin/ld: ../../_deps/openssl-source-build/libcrypto.a(libcrypto-lib-dso_dlfcn.o): in function `dlfcn_globallookup':
dso_dlfcn.c:(.text+0x17): undefined reference to `dlopen'
/usr/bin/ld: dso_dlfcn.c:(.text+0x2a): undefined reference to `dlsym'
/usr/bin/ld: dso_dlfcn.c:(.text+0x35): undefined reference to `dlclose'
/usr/bin/ld: ../../_deps/openssl-source-build/libcrypto.a(libcrypto-lib-dso_dlfcn.o): in function `dlfcn_bind_func':
dso_dlfcn.c:(.text+0x1cf): undefined reference to `dlsym'
/usr/bin/ld: dso_dlfcn.c:(.text+0x2ce): undefined reference to `dlerror'
/usr/bin/ld: ../../_deps/openssl-source-build/libcrypto.a(libcrypto-lib-dso_dlfcn.o): in function `dlfcn_load':
dso_dlfcn.c:(.text+0x345): undefined reference to `dlopen'
/usr/bin/ld: dso_dlfcn.c:(.text+0x3d0): undefined reference to `dlclose'
/usr/bin/ld: dso_dlfcn.c:(.text+0x401): undefined reference to `dlerror'
/usr/bin/ld: ../../_deps/openssl-source-build/libcrypto.a(libcrypto-lib-dso_dlfcn.o): in function `dlfcn_pathbyaddr':
dso_dlfcn.c:(.text+0x4d6): undefined reference to `dladdr'
/usr/bin/ld: dso_dlfcn.c:(.text+0x547): undefined reference to `dlerror'
/usr/bin/ld: ../../_deps/openssl-source-build/libcrypto.a(libcrypto-lib-dso_dlfcn.o): in function `dlfcn_unload':
dso_dlfcn.c:(.text+0x6d8): undefined reference to `dlclose'
collect2: error: ld returned 1 exit status

-------------------

It would b nice if you can give some tips to help me/


Thanks
Ajit






On Saturday, February 24, 2024 at 11:48:05 a.m. EST, Jiwoo Park ***@***.***> wrote: 







>  
> -- Curruent configure options : linux-;no-tests
> 

It seems like detecting the target platform has failed.
It should be linux-${CMAKE_SYSTEM_PROCESSOR} which is linux-x86_64 on your system.
Maybe CMAKE_SYSTEM_PROCESSOR wasn't set in the toolchain file?
You can also add set(OPENSSL_TARGET_PLATFORM linux-x86_64) before add_subdirectory(your_openssl_dir).

>  
> May be if you make a simple higher level CMakeLists with dependency of
> openssl 3,
> libssh2,
> zlib
> curl
> and make the build for this platform amd64-gnu and make it compilable
> that will be very helpful for me
> 

This project is just a CMake wrapper of OpenSSL build scripts. Combining those libraries isn't the purpose of this project.

**Comment by jimmy-park** [comment]
I have successfully built `libssh2` with `openssl-cmake`.
```cmake
cmake_minimum_required(VERSION 3.25)

project(geometry LANGUAGES CXX)

set(CMAKE_POLICY_DEFAULT_CMP0077 NEW)

set(BUILD_EXAMPLES OFF)
set(BUILD_TESTING OFF)

add_subdirectory(openssl-cmake)
add_subdirectory(libssh2)

add_dependencies(libssh2_static OpenSSL::SSL)
add_dependencies(libssh2_shared OpenSSL::SSL)

add_executable(app)
target_sources(app PRIVATE app.cpp)
target_link_libraries(app PRIVATE libssh2::libssh2)
```

For some reasons, dependencies don't work correctly. So I needed to set the build order explicitly using `add_dependencies()`. Examples and tests are also affected, but I just disabled them.

**Comment by mun24** [comment]
Thx a lot for the help. It is working now.

One more ask, is it possible to download openssl 3.0 manually one time and copy your CmakeLists in same folder and compile it when ever needed.

Thanks again



Regards
Ajit






On Sunday, February 25, 2024 at 11:44:39 p.m. EST, Jiwoo Park ***@***.***> wrote: 







I have successfully built libssh2 with openssl-cmake.

cmake_minimum_required(VERSION 3.25)

project(geometry LANGUAGES CXX)

set(CMAKE_POLICY_DEFAULT_CMP0077 NEW)

set(BUILD_EXAMPLES OFF)
set(BUILD_TESTING OFF)

add_subdirectory(openssl-cmake)
add_subdirectory(libssh2)

add_dependencies(libssh2_static OpenSSL::SSL)
add_dependencies(libssh2_shared OpenSSL::SSL)

add_executable(app)
target_sources(app PRIVATE app.cpp)
target_link_libraries(app PRIVATE libssh2::libssh2)

For some reasons, dependencies don't work correctly. So I needed to set the build order explicitly using add_dependencies(). Examples and tests are also affected, but I just disabled them.

**Comment by jimmy-park** [comment]
It is possible, but you need to do more work.
If you want to build local OpenSSL source, CMakeLists.txt should be modified.
https://github.com/jimmy-park/openssl-cmake/blob/a2a42b8c4bd2915f8eb523b564f9075311051e70/CMakeLists.txt#L61-L74
^^^ change this code as follows
```cmake
FetchContent_Declare(
    OpenSSL
    SOURCE_DIR ${local_openssl_source_dir}
    BINARY_DIR ${local_openssl_binary_dir}
    OVERRIDE_FIND_PACKAGE
)
FetchContent_MakeAvailable(OpenSSL)
```

**Comment by jimmy-park** [comment]
Now you can use the local OpenSSL source using `OPENSSL_SOURCE` option.

```cmake
set(OPENSSL_SOURCE "your-openssl-path")
add_subdirectory(openssl-cmake)
```

And `add_dependencies(libssh2_static OpenSSL::SSL)` will not be needed after https://github.com/libssh2/libssh2/pull/1322 is merged.
